const allMusic = [
  {
    name: "Mind of a Warrior",
    artist: "Alan Walker & Sorana",
    img: "assets/img/moaw.jpg",

    src: "Alan Walker - Mind of a Warrior",
  },
  {
    name: "Azizam",
    artist: "Ed Sheeran",
    img: "assets/img/azizam.jpeg",
    src: "Ed Sheeran - Azizam",
  },
  {
    name: "Sapphire",
    artist: "Ed Sheeran",
    img: "assets/img/sapphire.png",
    src: "Ed Sheeran - Sapphire",
  },
  {
    name: "Falling",
    artist: "Trevor Daniel",
    img: "assets/img/falling.jpg",
    src: "Trevor Daniel - Falling",
  },
  {
    name: "Thick of it All",
    artist: "Alan Walker ft. Jonas & Julia",
    img: "assets/img/toia.jpeg",
    src: "Alan Walker - Thick of it All",
  },
  {
    name: "21",
    artist: "Area 21",
    img: "assets/img/21.jpeg",
    src: "Area 21 - 21",
  },
  {
    name: "Beautiful People",
    artist: "David Guetta & Sia",
    img: "assets/img/beautiful-people.jpg",
    src: "David Guetta & Sia - Beautiful People",
  },
  {
    name: "Perfect",
    artist: "Ed Sheeran",
    img: "assets/img/perfect.jpg",
    src: "Ed Sheeran - Perfect",
  },
  {
    name: "Demons",
    artist: "Imagine Dragons",
    img: "assets/img/demons.jpg",
    src: "Imagine Dragons - Demons",
  },
  {
    name: "Alone",
    artist: "Marshmello",
    img: "assets/img/m-alone.jpg",
    src: "Marshmello - Alone",
  },
  {
    name: "World Apart",
    artist: "Marshmello & AR/DO",
    img: "assets/img/w-apart.jpeg",
    src: "Marshmello - World Apart",
  },
  {
    name: "Angels for each Other",
    artist: "Martin Garrix & Arijit Singh",
    img: "assets/img/afeo.jpeg",
    src: "Martin Garrix - Angels for each Other",
  },
  {
    name: "MAD",
    artist: "Martin Garrix & Lauv",
    img: "assets/img/mad.jpeg",
    src: "MAD",
  },
  {
    name: "Peace of Mind",
    artist: "Martin Garrix & Citadlle",
    img: "assets/img/pom.jpeg",
    src: "Martin Garrix - Peace of Mind",
  },
  {
    name: "Pressure",
    artist: "Martin Garrix",
    img: "assets/img/pressure.jpg",
    src: "Martin Garrix - Pressure",
  },
  {
    name: "Real Love",
    artist: "Martin Garrix",
    img: "assets/img/real-love.jpg",
    src: "Martin Garrix - Real Love",
  },
  {
    name: "Weightless",
    artist: "Martin Garrix & Arijit Singh",
    img: "assets/img/weightless.jpeg",
    src: "Martin Garrix - Weightless",
  },
  {
    name: "Sunflower",
    artist: "Post Malone",
    img: "assets/img/sunflower.jpg",
    src: "Post Malone - Sunflower",
  },
  {
    name: "Move your Body (Single mix)",
    artist: "Sia",
    img: "assets/img/myb.jpeg",
    src: "Sia - Move your Body (Single mix)",
  },
  {
    name: "Dandelions",
    artist: "Ruth B",
    img: "assets/img/dandelions.jpg",
    src: "Ruth B - Dandelions",
  },
  {
    name: "Ascend (VIP Mix)",
    artist: "Vluarr & Arcando",
    img: "assets/img/ascend.jpg",
    src: "Vluarr - Ascend (VIP Remix)",
  },
  {
    name: "Me, Myself and The Night",
    artist: "Alan Walker",
    img: "assets/img/AW - MMN.jpeg",
    src: "Alan Walker - Me, Myself and The Night",
  },
];
