const allMusic = [
  {
    name: "Mind of a Warrior",
    artist: "Alan Walker",
    img: "",
    src: "Alan Walker - Mind of a Warrior",
  },
  {
    name: "Azizam",
    artist: "Ed Sheeran",
    img: "",
    src: "Ed Sheeran - Azizam",
  },
  {
    name: "Sapphire",
    artist: "Ed Sheeran",
    img: "",
    src: "Ed Sheeran - Sapphire",
  },
  {
    name: "Falling",
    artist: "Trevor Daniel",
    img: "",
    src: "Trevor Daniel - Falling",
  },
  {
    name: "Thick of it All",
    artist: "Alan Walker",
    img: "",
    src: "Alan Walker - Thick of it All",
  },
  {
    name: "21",
    artist: "Area 21",
    img: "",
    src: "Area 21 - 21",
  },
  {
    name: "Beautiful People",
    artist: "David Guetta & Sia",
    img: "",
    src: "David Guetta & Sia - Beautiful People",
  },
  {
    name: "Perfect",
    artist: "Ed Sheeran",
    img: "",
    src: "Ed Sheeran - Perfect",
  },
  {
    name: "Demons",
    artist: "Imagine Dragons",
    img: "",
    src: "Imagine Dragons - Demons",
  },
  {
    name: "Alone",
    artist: "Marshmello",
    img: "",
    src: "Marshmello - Alone",
  },
  {
    name: "World Apart",
    artist: "Marshmello",
    img: "",
    src: "Marshmello - World Apart",
  },
  {
    name: "Angels for each Other",
    artist: "Martin Garrix",
    img: "",
    src: "Martin Garrix - Angels for each Other",
  },
  {
    name: "MAD",
    artist: "Martin Garrix & Lauv",
    img: "",
    src: "MAD",
  },
  {
    name: "Peace of Mind",
    artist: "Martin Garrix & Citadlle",
    img: "",
    src: "Martin Garrix - Peace of Mind",
  },
  {
    name: "Pressure",
    artist: "Martin Garrix",
    img: "",
    src: "Martin Garrix - Pressure",
  },
  {
    name: "Real Love",
    artist: "Martin Garrix",
    img: "",
    src: "Martin Garrix - Real Love",
  },
  {
    name: "Weightless",
    artist: "Martin Garrix",
    img: "",
    src: "Martin Garrix - Weightless",
  },
  {
    name: "Sunflower",
    artist: "Post Malone",
    img: "",
    src: "Post Malone - Sunflower",
  },
  {
    name: "Move your Body (Single mix)",
    artist: "Sia",
    img: "",
    src: "Sia - Move your Body (Single mix)",
  },
  {
    name: "Dandelions",
    artist: "Ruth B",
    img: "",
    src: "Ruth B - Dandelions",
  },
  {
    name: "Ascend (VIP Mix)",
    artist: "Vluarr",
    img: "",
    src: "Vluarr - Ascend (VIP Remix)",
  },
  {
    name: "Me, Myself and The Night",
    artist: "Alan Walker",
    img: "AW - MMN",
    src: "Alan Walker - Me, Myself and The Night",
  },
];
